services:
  db:
    image: postgres:16
    container_name: data_analyzer
    restart: unless-stopped
    environment:
      POSTGRES_USER: enrique
      POSTGRES_PASSWORD: 25450712
      POSTGRES_DB: data_analyzer
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
